on:
  pull_request:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
      
      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v3
        with:
          name: DataExtractor-Windows-X64-${{ github.sha }}
          path: |
              build/windows/x64/release/DataExtractor.dll
              build/windows/x64/release/DataExtractor.pdb
