on:
  push:
    branches:
      - master
      - workflow
    paths:
      - .github/workflows/build.yml
      - scripts/localbdslibrary.lua
      - src/**
      - xmake.lua
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - scripts/localbdslibrary.lua
      - src/**
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Read bdsversion file
        id: read-version
        run: |
          VERSION_TYPE=$(grep -oP 'type=\K[^,]+' bdsversion)
          VERSION_NUMBER=$(grep -oP 'version=\K[^,]+' bdsversion)
          echo "version_type=${VERSION_TYPE}" >> $GITHUB_ENV
          echo "version_number=${VERSION_NUMBER}" >> $GITHUB_ENV

      - uses: xmake-io/github-action-setup-xmake@v1
  
      - uses: actions/cache@v3
        with:
          path: |
            ~/AppData/Local/.xmake
            .xmake
            build/bds/lib
          key: |
            xmake-dataextractor-windows-x64-${{ github.sha }}
            xmake-dataextractor-windows-x64-${{ github.sha }}
            bdslib-${{ env.version_type }}-${{ env.version_number }}
          restore-keys: |
            xmake-dataextractor-windows-x64-
            xmake-dataextractor-windows-x64-

      - run: |
          xmake repo -u

      - run: |
          xmake bds-lib -b --${{ env.version_type }}=${{ env.version_number }}

      - run: |
          xmake f -a x64 -m release -p windows -v -y --ccache=n

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v3
        with:
          name: DataExtractor-Windows-X64-${{ github.sha }}
          path: |
            build/windows/x64/release/DataExtractor.dll
            build/windows/x64/release/DataExtractor.pdb